import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import styles from "./index.module.css";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

export default function Home() {
  const utils = api.useUtils();
  const { data } = api.chart.getDiseaseMetrics.useQuery();
  const { mutateAsync: toggleFavoriteChart } =
    api.chart.toggleFavoriteChart.useMutation({
      onSuccess: ({ diseaseChart }) => {
        const previousData = utils.chart.getDiseaseMetrics.getData();

        const newData = previousData?.map((chartData) =>
          chartData.id === diseaseChart?.id
            ? { ...chartData, isFavorite: diseaseChart?.isFavorite }
            : chartData
        );
        utils.chart.getDiseaseMetrics.setData(undefined, () => newData);
      },
    });
  // NOTE: Dummy test

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>First Steps →</h3>
              <div className={styles.cardText}>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Documentation →</h3>
              <div className={styles.cardText}>
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          {data?.map((diseaseChart) => (
            <div key={diseaseChart.id}>
              <div style={{ color: "white" }}>
                {diseaseChart.title} {diseaseChart.id}
              </div>
              <button
                onClick={() =>
                  toggleFavoriteChart({
                    chartId: diseaseChart.id!,
                    isFavorite: !diseaseChart.isFavorite,
                  })
                }
              >
                {diseaseChart.isFavorite ? "Unlike me" : "Like me"}
              </button>
              <BarChart width={730} height={250} data={diseaseChart.results}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="date" />
                <YAxis dataKey="metric_value" />
                <Tooltip />

                <Legend />
                <Bar dataKey="metric_value" fill="#8884d8" />
              </BarChart>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
