import Head from "next/head";
import { Button, Flex } from "antd";
import { api } from "~/utils/api";
import styles from "./index.module.css";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

export default function Home() {
  const utils = api.useUtils();
  const { data } = api.chart.getDiseaseMetrics.useQuery();
  const { mutateAsync: toggleFavoriteChart } =
    api.chart.toggleFavoriteChart.useMutation({
      onSuccess: ({ diseaseChart }) => {
        const previousData = utils.chart.getDiseaseMetrics.getData();

        const newData = previousData?.map((chartData) =>
          chartData.id === diseaseChart?.id
            ? { ...chartData, isFavorite: diseaseChart?.isFavorite }
            : chartData
        );
        utils.chart.getDiseaseMetrics.setData(undefined, () => newData);
      },
    });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          {data?.map((diseaseChart) => (
            <div key={diseaseChart.id}>
              <Flex vertical gap="middle">
                <div style={{ color: "white" }}>
                  {diseaseChart.title} {diseaseChart.id}
                </div>
                <Button
                  onClick={() =>
                    toggleFavoriteChart({
                      chartId: diseaseChart.id!,
                      isFavorite: !diseaseChart.isFavorite,
                    })
                  }
                >
                  {diseaseChart.isFavorite ? "Unlike me" : "Like me"}
                </Button>
              </Flex>
              <BarChart width={730} height={250} data={diseaseChart.results}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="date" />
                <YAxis dataKey="metric_value" />
                <Tooltip />

                <Legend />
                <Bar dataKey="metric_value" fill="#8884d8" />
              </BarChart>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
